services:
  ppv-hls-proxy:
    build:
      context: .
    pull_policy: missing
    container_name: ppv-hls-proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "${PORT:-3000}:3000"
    restart: always
